import type { Metadata } from 'next'
import './global.css';
import Header from '@/components/BasicNet/Header/Header';
import { Inter } from 'next/font/google';
import ReduxProviders from './store/Provider'



const inter = Inter({
  subsets: ['latin'],
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'Thoughts',
  description: 'Generated by create next app',
  icons: {
   icon: './icon.ico'
  }
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
    <html lang="en">
        <body className={inter.className}>
          <ReduxProviders>
            <Header />
            <main className='wrapper'>
              
                {children}
            
            </main>
          </ReduxProviders>
        </body>
    </html>
  )
}
